title: EatherSec
description: Your source for insight and confidence in the world of cyber security
baseurl: "" # Only set if using a subfolder
url: "https://espenssk.github.io"
# theme: minima  # REMOVE this to use your own layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag
